server:
  port: 9001

spring:
  application:
    name: location-manager-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database:  lmsDb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
