server:
  port: 9000

spring:
  application:
    name: product-manager-service
  data:
    mongodb:
     host: localhost
     port: 27017
     database: pmsDb

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

